### ISSUE TITLE
'$' appearing in path to solution on xamarin ios builds

### ISSUE THREAD

**Issue by rusty21** [Microsoft/vso-agent#115] opened 2015-10-13 20:43 UTC
Build processes is failing because it can't find the solution file. There appears to be an extra $ in the path.

invalid solution: /agent/_work/1/s/$/TestProject/test.sln
/usr/bin/nuget restore /agent/_work/1/s/$/TestProject/test.sln
Cannot locate a solution file.
/usr/bin/nuget failed with return code: 1

On the Xamarin.iOS build the solution is pointing to $/TestProject/test.sln

**Comment by yacaovsnc** [comment] 2015-10-13 20:48
@rusty21 In the build definition, you can specify the test.sln path directly. For TFVC projects, we remove the longest common parent directory before we map the workspace to reduce the path length.  In this case I am guessing you need to update the build definition and in the solution field, use 'test.sln' instead of '$/TestProject/test.sln'.

**Comment by rusty21** [comment] 2015-10-13 21:26
Turns out just having the solution file wasn't enough I needed to have the folder it was contained in also. What needed to be in the build definition was "TestProject/test.sln". That being said on the build definition there is a button with 3 dots on it that allows you to browse for your solution file. When I did that, this got entered into the solution box "$/TestProject/test.sln". I can't be the only one who is going to do this, perhaps you should still handle the case where the $ exists on the vso agent, or make it so that it doesn't appear when clicking the 3 dots button to browse for the solution.

**Comment by bryanmacfarlane** [comment] 2015-10-13 21:38
@rusty21 - I agree.  we should handle this.

**Comment by ossentoo** [comment] 2015-12-17 23:38
I did exactly the same thing.  Fortunately I found this post after a couple of hours of searching for solutions.  I'm sure those using the xamarin build step would appreciate a change to make this work more seamlessly.

**Comment by yacaovsnc** [comment] 2015-12-18 15:16
@ossentoo thanks for providing your input. The problem is we change the source folder structure during TFVC xplat build -- we need to eliminate common paths among mappings so we don't exceed TFVC workspace path limit.  So your solution at "$/a/b.sln" could be either "a/b.sln" or "b.sln" depending on your mappings.  It's not limited to Xamarin build.

I think the right thing to do is implement server/local mapping in the xplat client and remove the "..." (repo file selector) for this solution.  Then we would have exposed everything we need to make sure the mappings in repository tab and the inputs on tasks are in sync.  It wouldn't be a guessing game anymore.  

I will sleep on this for couple days and try to make some improvements.  

Thanks all for your valuable feedback.

**Comment by ossentoo** [comment] 2015-12-18 16:01
ok @yacaovsnc  thanks for the response.

**Comment by bryanmacfarlane** [comment] 2016-01-31 10:21
This should be fixed I believe with the latest preview agent (0.5).  Yang, can you confirm?

**Closed** 2016-02-24 01:55 UTC
