### ISSUE TITLE
failed to compile TypeScript TS1144

### ISSUE THREAD

**Issue by jsnmc** [Microsoft/vso-agent#250] opened 2016-03-14 00:30 UTC
E:\Code\Scratch\Repos\vso-agent-tasks
[18:15:46] Compiling TypeScript files using tsc version 1.8.7
[18:15:47] [tsc] > definitions/shelljs.d.ts(473,88): t '{' or ';' ex
pected.
[18:15:49] Failed to compile TypeScript: Error: tsc command has exited with code
:2

Line 473 :` export function exec(command: string, options: ExecOptions): ExecOutputReturnValue | child.ChildProcess;`

events.js:141
      throw er; // Unhandled 'error' event
      ^
 Error: Failed to compile: tsc command has exited with code:2

**Comment by ankitgo** [comment] 2016-03-14 07:42
Duplicate of 236.
https://github.com/Microsoft/vso-agent/issues/236

**Comment by bryanmacfarlane** [comment] 2016-03-29 20:22
The output above shows you building the tasks repo, not this one.  This is external.  but, I did recently take some commits to get this repo to build with 1.8.7

**Closed by bryanmacfarlane** 2016-03-29 20:22 UTC
