### ISSUE TITLE
Can't publish build artifacts

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vso-agent#45] opened 2015-07-31 13:11 UTC
I added a **Publish Build Artifacts** step, but it always fails with an error:

```
2015-07-31T12:58:53.920Z: Cleaning staging folder: /vso/work/build/e77e2255f478cdc1bc5f4775e7d7cc6c159410e4c8bda1b698b41a91d1bfaec1/staging/Editor
2015-07-31T12:58:56.303Z: found 323 files
2015-07-31T12:58:59.740Z:  
2015-07-31T12:58:59.740Z: Start: Upload a build artifact
2015-07-31T12:58:59.740Z: End: Upload a build artifact
2015-07-31T12:58:59.740Z:  
##[Error] 2015-07-31T12:58:59.741Z: No container folder specified.
2015-07-31T12:58:59.741Z: Failing task since command failed.
```

Here's the configuration:

![image](https://cloud.githubusercontent.com/assets/22350/9007857/bc7adbd4-3795-11e5-80a9-fd3739a32f53.png)

It feels like there's something missing in the UI, especially since the code goes looking for a [`containerfolder` property](https://github.com/Microsoft/vso-agent/blob/7bdc33003f732afb2f38571732a102c9ea108688/src/agent/commands/artifact.upload.ts#L26).

**Comment by bryanmacfarlane** [comment] 2015-07-31 13:15
We'll investigate.

If you go to the variables tab and set 
system.debug true

Does that add any info that helps?

**Comment by joaomoreno** [comment] 2015-07-31 13:26
I can see that the agent creates a `staging/Editor` directory and successfully copies all the files in there. After copying it just fails with that error... no interesting stuff in there.

**Comment by joaomoreno** [comment] 2015-08-03 08:58
I confirm that it works when running the build in a Windows agent (not this project).

**Comment by bryanmacfarlane** [comment] 2015-08-17 11:13
assigning to Scott

**Comment by jdrake3** [comment] 2015-12-08 15:03
Having the same issue, any progress or ETA?

**Comment by bryanmacfarlane** [comment] 2016-02-24 01:56
Scott?

**Comment by scottdallamura** [comment] 2016-02-24 14:26
I was unable to reproduce this.  Is it still happening?

**Comment by jdrake3** [comment] 2016-04-01 00:51
Scott,

My particular issue was resolved with a separate fix having to do with deployment slots and the task template itself has since updated too.

**Closed** 2016-04-22 01:35 UTC

**Comment by joaomoreno** [comment] 2016-04-22 07:54
I worked around the problem almost a year ago.
