### ISSUE TITLE
http://xxx is not a valid URL

### ISSUE THREAD

**Issue by finortis** [Microsoft/vso-agent#32] opened 2015-06-22 12:13 UTC
We just upgraded our on-premise TFS server from 2013->2015 RC last week. I have done all of the setup steps on a Yosemite OSX build (Xamarin) server but when I attempt to configure the agent, I always get...

Error starting the agent
http://xxx is not a valid URL

FYI, I have tried a variety of different flavors of the URL - some with the 8080 port, some without, some with the default collection, some without.

What am I doing wrong?

**Comment by bryanmacfarlane** [comment] 2015-06-22 12:57
which url string is used for the agent? from the agent root
cat .agent

**Comment by bryanmacfarlane** [comment] 2015-08-17 11:18
This was fixed with a recent pull request.  The issue is it failed with a non-FQDN url

**Closed by bryanmacfarlane** 2015-08-17 11:18 UTC
