### ISSUE TITLE
CopyPublishBuildArtifacts and CopyFiles tasks no longer work on Linux CentOS 7.1

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vso-agent#160] opened 2015-11-25 20:24 UTC
I have the agent running on Linux CentOS 7.1. Everything is latest versions or thereabout.

At some point my VSO builds started to fail because `CopyPublishBuildArtifacts` stopped working.

After some investigation and trying everything (including upgrading everything to latest version including node and vso-agent and completely reinstalling from scratch) and all possible configurations and tick boxes, the issue is still there.

It seems related to and looks same as with `CopyFiles` task, which also fails.

There are no error messages or anything, it just dies without explanation. Nothing in the log files in the VSO agent directories that I can see.

It all worked on 19 Nov 2015. Then on 24 Nov it wasn't working anymore, and I haven't made any changes to anything.

Here is the output of the failed `CopyFiles` task

```
##[Debug] 2015-11-25T19:48:45.271Z: SourceFolder: /home/philip/vsoagent/_work/2/s
##[Debug] 2015-11-25T19:48:45.272Z: Contents: /home/philip/vsoagent/_work/2/s/folder/folder/folder/file.jar
##[Debug] 2015-11-25T19:48:45.272Z: TargetFolder: /tmp
##[Debug] 2015-11-25T19:48:45.272Z: CleanTargetFolder: false
##[Debug] 2015-11-25T19:48:45.272Z: OverWrite: true
##[Debug] 2015-11-25T19:48:45.278Z: 
##[Debug] 2015-11-25T19:48:45.280Z: cwd: /home/philip/vsoagent/_work/2/s
```

Here is the output of the failed `CopyPublishBuildArtifacts` -- note how similar it is to `CopyFiles`

```
##[Debug] 2015-11-25T20:12:52.253Z: CopyRoot: /home/philip/vsoagent/_work/2/s
##[Debug] 2015-11-25T20:12:52.254Z: Contents: **/*/file.jar
##[Debug] 2015-11-25T20:12:52.254Z: ArtifactName: whatever
##[Debug] 2015-11-25T20:12:52.254Z: ArtifactType: Container
##[Debug] 2015-11-25T20:12:52.254Z: TargetPath: \\my\share\build-definition-name\build-number
##[Debug] 2015-11-25T20:12:52.254Z: 
##[Debug] 2015-11-25T20:12:52.261Z: cwd: /home/philip/vsoagent/_work/2/s
```

I tried the same `CopyPublishBuildArtifacts` on a hosted agent (which is Windows) and it worked. So assume the issue is Linux-specific.

**Comment by noisygerman** [comment] 2015-12-02 23:40
I've encountered the same problem on Azure Ubuntu 14.04 hosted on an Azure Linux VM. Does anybody have any insights? Could this be related to permission settings potentially?

Debug output:

```
******************************************************************************
Running CopyPublishBuildArtifacts
******************************************************************************
CopyRoot: /home/shared/linuxagent01/_work/2/a
Contents: WebUi-Build-181.zip
ArtifactName: WebUiPackage
ArtifactType: Container
TargetPath:
cwd: /home/shared/linuxagent01/_work/2/s
```

**Comment by noisygerman** [comment] 2015-12-03 01:00
Digging further this actually seems to be related to the `copy` task, not `publish`. If I run `Copy` in isolation, i get a similar issue, while `Publish` in isolation succeeds: 

```
******************************************************************************
Running CopyFiles
******************************************************************************
SourceFolder: /home/shared/linuxagent01/_work/2/a
Contents: MVWebUi-Build-181.zip
TargetFolder: /home/shared/linuxagent01/_work/2/a/Build-181/MVWebUi.zip
CleanTargetFolder: true
OverWrite: true
cwd: /home/shared/linuxagent01/_work/2/s
```

**Comment by bryanmacfarlane** [comment] 2015-12-03 01:04
Ting can have a look

**Comment by TingluoHuang** [comment] 2016-01-18 15:17
This is caused by case sensitive file name on Linux. 
In task.json, the node execution section's target is "copyFiles.js", however the actual file in the task folder is "CopyFiles.js". this is because all tasks package are generated on a windows build machine. with M94 rolls out, all task's .js file name should be lowercase, and we have an unit test make sure we won't break it anymore.

**Comment by noisygerman** [comment] 2016-01-18 18:59
@TingluoHuang Thanks, Ting, much appreciated.

**Comment by julienstroheker** [comment] 2016-01-20 00:06
Thanks Ting,
FYI I renamed my CopyPublishBuildArtifacts.js to copyPublishBuildArtifacts.js as mentined in my task.json file in the _work/taks/CopyPublishBuildArtifacts/...
It works as workaround :)

**Comment by bryanmacfarlane** [comment] 2016-01-31 10:10
This should have been patched as well to the service.  closing

**Closed by bryanmacfarlane** 2016-01-31 10:10 UTC
