### ISSUE TITLE
OSX service installation stores credentials in plaintext

### ISSUE THREAD

**Issue by jkeech** [Microsoft/vso-agent#184] opened 2016-01-07 20:23 UTC
If you install the agent as a service on OSX, the generated plist file contains the credentials in plaintext. It seems like a better approach might be to use the keychain to store the password/token and then the agent could retrieve the password from the keychain at runtime.

**Comment by bryanmacfarlane** [comment] 2016-01-07 20:24
dupe of #40

**Closed by bryanmacfarlane** 2016-01-07 20:24 UTC
