### ISSUE TITLE
 TFS Version Control is not supported yet?

### ISSUE THREAD

**Issue by RuudHbm** [Microsoft/vso-agent#63] opened 2015-08-19 08:11 UTC
Using sudo npm install vsoagent-installer -g (as the README.md states) installs an older version of vsoagent which does not support TFS version control.

**Comment by bryanmacfarlane** [comment] 2015-08-19 12:31
It's in master, undergoing testing and will release to npm very soon

Dupe of this issue: https://github.com/Microsoft/vso-agent/issues/24

**Closed by bryanmacfarlane** 2015-08-19 12:31 UTC

**Comment by dylanberry** [comment] 2015-10-05 19:08
Was this released to npm? I installed today and I'm getting the same message: "TFS Version Control is not supported on xplat yet".

**Comment by rusty21** [comment] 2015-10-08 17:46
Also seeing this error. Wasn't this suppose to be released not long after Aug 19?

**Comment by bryanmacfarlane** [comment] 2015-10-08 18:36
It got delayed because we had to implement shorter paths for TfsVc: https://github.com/Microsoft/vso-agent/blob/master/docs/workfolder.md

That required completely reworking how we manage workspaces on disk

See the bottom of the readme on how to install 0.3 preview with all the changes

**Comment by rusty21** [comment] 2015-10-09 12:52
I was able to install the preview version but during getting latest I got a path too long error, is there any work around for this?

**Comment by bryanmacfarlane** [comment] 2015-10-09 14:07
It was fixed this morning and I just release preview 0.3.4 - even though we had the shorter root path described in workfolder docs above, it was still using the long hash folder.

I would recommend just installing a new preview agent.

Here's the PR: https://github.com/Microsoft/vso-agent/pull/108
